import 'package:flutter/material.dart';
import 'package:flutterapp/joyeriaapp/generatedbarrawidget1/generated/GeneratedPerfilWidget2.dart';
import 'package:flutterapp/joyeriaapp/generatedbarrawidget1/generated/GeneratedBarranegraWidget1.dart';
import 'package:flutterapp/joyeriaapp/generatedbarrawidget1/generated/GeneratedAjustesWidget2.dart';
import 'package:flutterapp/joyeriaapp/generatedbarrawidget1/generated/GeneratedProductosWidget2.dart';
import 'package:flutterapp/joyeriaapp/generatedbarrawidget1/generated/GeneratedInicioWidget3.dart';

/* Component Barra
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBarraWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.only(
        topLeft: Radius.circular(20.0),
        topRight: Radius.circular(20.0),
        bottomRight: Radius.circular(0.0),
        bottomLeft: Radius.circular(0.0),
      ),
      child: Container(
        width: 412.0,
        height: 78.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.only(
            topLeft: Radius.circular(20.0),
            topRight: Radius.circular(20.0),
            bottomRight: Radius.circular(0.0),
            bottomLeft: Radius.circular(0.0),
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 0.0,
                top: 1.0,
                right: null,
                bottom: null,
                width: 424.0,
                height: 87.0,
                child: GeneratedBarranegraWidget1(),
              ),
              Positioned(
                left: 24.0,
                top: 15.0,
                right: null,
                bottom: null,
                width: 47.0,
                height: 46.0,
                child: GeneratedInicioWidget3(),
              ),
              Positioned(
                left: 263.0,
                top: 17.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 44.0,
                child: GeneratedPerfilWidget2(),
              ),
              Positioned(
                left: 335.0,
                top: 16.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 44.0,
                child: GeneratedAjustesWidget2(),
              ),
              Positioned(
                left: 94.0,
                top: 17.0,
                right: null,
                bottom: null,
                width: 58.0,
                height: 44.0,
                child: GeneratedProductosWidget2(),
              )
            ]),
      ),
    ));
  }
}
