import 'package:flutter/material.dart';
import 'package:flutterapp/joyeriaapp/generatedpaquete1widget1/generated/GeneratedVectorWidget41.dart';
import 'package:flutterapp/joyeriaapp/generatedpaquete1widget1/generated/GeneratedFrame3Widget1.dart';
import 'package:flutterapp/joyeriaapp/generatedpaquete1widget1/generated/GeneratedPaquete12Widget1.dart';
import 'package:flutterapp/joyeriaapp/generatedpaquete1widget1/generated/Generated\$9999Widget4.dart';
import 'package:flutterapp/joyeriaapp/generatedpaquete1widget1/generated/GeneratedBuscadorWidget6.dart';
import 'package:flutterapp/joyeriaapp/generatedpaquete1widget1/generated/GeneratedPaquetedebrasaletesPDamadeOroWidget.dart';
import 'package:flutterapp/joyeriaapp/generatedpaquete1widget1/generated/GeneratedRectangle19Widget1.dart';
import 'package:flutterapp/joyeriaapp/generatedpaquete1widget1/generated/GeneratedProductossimilaresWidget1.dart';
import 'package:flutterapp/joyeriaapp/generatedpaquete1widget1/generated/GeneratedVectorWidget40.dart';
import 'package:flutterapp/joyeriaapp/generatedpaquete1widget1/generated/GeneratedRectangle21Widget1.dart';

/* Frame Paquete1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPaquete1Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 410.0,
        height: 739.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 200, 66, 66),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 389.0,
                right: null,
                bottom: null,
                width: 410.0,
                height: 350.0,
                child: GeneratedRectangle19Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 104.0,
                right: null,
                bottom: null,
                width: 410.0,
                height: 273.0,
                child: GeneratedPaquete12Widget1(),
              ),
              Positioned(
                left: 11.0,
                top: 14.0,
                right: null,
                bottom: null,
                width: 388.0,
                height: 71.0,
                child: GeneratedBuscadorWidget6(),
              ),
              Positioned(
                left: 12.0,
                top: 117.0,
                right: null,
                bottom: null,
                width: 8.4375,
                height: 16.875,
                child: GeneratedVectorWidget40(),
              ),
              Positioned(
                left: 16.0,
                top: 479.0,
                right: null,
                bottom: null,
                width: 146.0,
                height: 46.0,
                child: Generated$9999Widget4(),
              ),
              Positioned(
                left: 16.0,
                top: 408.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 93.0,
                child: GeneratedPaquetedebrasaletesPDamadeOroWidget(),
              ),
              Positioned(
                left: 30.0,
                top: 531.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 41.0,
                child: GeneratedRectangle21Widget1(),
              ),
              Positioned(
                left: 47.0,
                top: 538.0,
                right: null,
                bottom: null,
                width: 184.0,
                height: 28.0,
                child: GeneratedProductossimilaresWidget1(),
              ),
              Positioned(
                left: 13.0,
                top: 579.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 160.0,
                child: GeneratedFrame3Widget1(),
              ),
              Positioned(
                left: 376.0,
                top: 113.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 27.0,
                child: GeneratedVectorWidget41(),
              )
            ]),
      ),
    ));
  }
}
