import 'package:flutter/material.dart';
import 'package:flutterapp/joyeriaapp/generatedpaquete1widget/generated/GeneratedProductossimilaresWidget.dart';
import 'package:flutterapp/joyeriaapp/generatedpaquete1widget/generated/GeneratedRectangle21Widget.dart';
import 'package:flutterapp/joyeriaapp/generatedpaquete1widget/generated/GeneratedVectorWidget32.dart';
import 'package:flutterapp/joyeriaapp/generatedpaquete1widget/generated/GeneratedPaquete12Widget.dart';
import 'package:flutterapp/joyeriaapp/generatedpaquete1widget/generated/Generated\$9999Widget2.dart';
import 'package:flutterapp/joyeriaapp/generatedpaquete1widget/generated/GeneratedRectangle19Widget.dart';
import 'package:flutterapp/joyeriaapp/generatedpaquete1widget/generated/GeneratedConjuntodeJoyeriaBrasaleteAretesCollarWidget.dart';
import 'package:flutterapp/joyeriaapp/generatedpaquete1widget/generated/GeneratedBuscadorWidget4.dart';
import 'package:flutterapp/joyeriaapp/generatedpaquete1widget/generated/GeneratedFrame3Widget.dart';
import 'package:flutterapp/joyeriaapp/generatedpaquete1widget/generated/GeneratedVectorWidget33.dart';

/* Frame Paquete1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPaquete1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 410.0,
        height: 739.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 200, 66, 66),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 389.0,
                right: null,
                bottom: null,
                width: 410.0,
                height: 350.0,
                child: GeneratedRectangle19Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 104.0,
                right: null,
                bottom: null,
                width: 410.0,
                height: 273.0,
                child: GeneratedPaquete12Widget(),
              ),
              Positioned(
                left: 11.0,
                top: 14.0,
                right: null,
                bottom: null,
                width: 388.0,
                height: 71.0,
                child: GeneratedBuscadorWidget4(),
              ),
              Positioned(
                left: 12.0,
                top: 117.0,
                right: null,
                bottom: null,
                width: 8.4375,
                height: 16.875,
                child: GeneratedVectorWidget32(),
              ),
              Positioned(
                left: 16.0,
                top: 479.0,
                right: null,
                bottom: null,
                width: 146.0,
                height: 46.0,
                child: Generated$9999Widget2(),
              ),
              Positioned(
                left: 16.0,
                top: 408.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 93.0,
                child: GeneratedConjuntodeJoyeriaBrasaleteAretesCollarWidget(),
              ),
              Positioned(
                left: 30.0,
                top: 531.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 41.0,
                child: GeneratedRectangle21Widget(),
              ),
              Positioned(
                left: 47.0,
                top: 538.0,
                right: null,
                bottom: null,
                width: 184.0,
                height: 28.0,
                child: GeneratedProductossimilaresWidget(),
              ),
              Positioned(
                left: 13.0,
                top: 579.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 160.0,
                child: GeneratedFrame3Widget(),
              ),
              Positioned(
                left: 376.0,
                top: 113.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 27.0,
                child: GeneratedVectorWidget33(),
              )
            ]),
      ),
    ));
  }
}
