import 'package:flutter/material.dart';
import 'package:flutterapp/joyeriaapp/generatedbienvenidawidget/generated/GeneratedBievenidoaNuestraTiendaWidget.dart';
import 'package:flutterapp/joyeriaapp/generatedbienvenidawidget/generated/GeneratedRectangle22Widget2.dart';
import 'package:flutterapp/joyeriaapp/generatedbienvenidawidget/generated/GeneratedSTREETSTYLE_freefile3Widget1.dart';
import 'package:flutterapp/joyeriaapp/generatedbienvenidawidget/generated/GeneratedFrame6Widget.dart';

/* Frame Bienvenida
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBienvenidaWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 410.0,
        height: 739.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 0.0,
                top: 64.0,
                right: null,
                bottom: null,
                width: 410.0,
                height: 675.0,
                child: GeneratedRectangle22Widget2(),
              ),
              Positioned(
                left: 72.0,
                top: 184.0,
                right: null,
                bottom: null,
                width: 267.0,
                height: 300.0,
                child: GeneratedSTREETSTYLE_freefile3Widget1(),
              ),
              Positioned(
                left: 45.0,
                top: 101.0,
                right: null,
                bottom: null,
                width: 321.0,
                height: 44.0,
                child: GeneratedBievenidoaNuestraTiendaWidget(),
              ),
              Positioned(
                left: 34.0,
                top: 530.0,
                right: null,
                bottom: null,
                width: 341.0,
                height: 70.0,
                child: GeneratedFrame6Widget(),
              )
            ]),
      ),
    ));
  }
}
