import 'package:flutter/material.dart';
import 'package:flutterapp/joyeriaapp/generatediniciowidget/generated/GeneratedHombresRockPunkenformadecubocolgantecollar4coloresAcero.dart';
import 'package:flutterapp/joyeriaapp/generatediniciowidget/generated/GeneratedFondoWidget.dart';
import 'package:flutterapp/joyeriaapp/generatediniciowidget/generated/GeneratedBuscadorWidget.dart';
import 'package:flutterapp/joyeriaapp/generatediniciowidget/generated/GeneratedSTREETSTYLE_freefile1Widget.dart';
import 'package:flutterapp/joyeriaapp/generatediniciowidget/generated/GeneratedProducto1Widget.dart';
import 'package:flutterapp/joyeriaapp/generatediniciowidget/generated/GeneratedPaquete3Widget.dart';
import 'package:flutterapp/joyeriaapp/generatediniciowidget/generated/GeneratedJoyeriasenmonterrey1Widget.dart';
import 'package:flutterapp/joyeriaapp/generatediniciowidget/generated/GeneratedBarraWidget.dart';
import 'package:flutterapp/joyeriaapp/generatediniciowidget/generated/GeneratedSpostophotography1Widget.dart';
import 'package:flutterapp/joyeriaapp/generatediniciowidget/generated/GeneratedPaquete21Widget.dart';

/* Frame Inicio
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedInicioWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 410.0,
        height: 739.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 102, 153, 182),
                ),
              ),
              Positioned(
                left: -2.0,
                top: 95.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 559.0,
                child: GeneratedFondoWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 661.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 78.0,
                child: GeneratedBarraWidget(),
              ),
              Positioned(
                left: 61.0,
                top: 208.0,
                right: null,
                bottom: null,
                width: 288.0,
                height: 324.0,
                child: GeneratedSTREETSTYLE_freefile1Widget(),
              ),
              Positioned(
                left: 11.0,
                top: 310.0,
                right: null,
                bottom: null,
                width: 180.0,
                height: 150.0,
                child: GeneratedPaquete3Widget(),
              ),
              Positioned(
                left: 218.0,
                top: 310.0,
                right: null,
                bottom: null,
                width: 180.0,
                height: 150.0,
                child: GeneratedSpostophotography1Widget(),
              ),
              Positioned(
                left: 11.0,
                top: 480.0,
                right: null,
                bottom: null,
                width: 180.0,
                height: 150.0,
                child:
                    GeneratedHombresRockPunkenformadecubocolgantecollar4coloresAcero(),
              ),
              Positioned(
                left: 218.0,
                top: 480.0,
                right: null,
                bottom: null,
                width: 179.1946258544922,
                height: 150.0,
                child: GeneratedJoyeriasenmonterrey1Widget(),
              ),
              Positioned(
                left: 11.0,
                top: 141.0,
                right: null,
                bottom: null,
                width: 180.0,
                height: 149.0,
                child: GeneratedProducto1Widget(),
              ),
              Positioned(
                left: 10.0,
                top: 14.0,
                right: null,
                bottom: null,
                width: 388.0,
                height: 71.0,
                child: GeneratedBuscadorWidget(),
              ),
              Positioned(
                left: 219.0,
                top: 141.0,
                right: null,
                bottom: null,
                width: 180.0,
                height: 150.0,
                child: GeneratedPaquete21Widget(),
              )
            ]),
      ),
    ));
  }
}
