import 'package:flutter/material.dart';
import 'package:flutterapp/joyeriaapp/generatediniciodesecionwidget/generated/GeneratedIngresatuCorreoElectronicoWidget.dart';
import 'package:flutterapp/joyeriaapp/generatediniciodesecionwidget/generated/GeneratedVectorWidget47.dart';
import 'package:flutterapp/joyeriaapp/generatediniciodesecionwidget/generated/GeneratedBotonWidget1.dart';
import 'package:flutterapp/joyeriaapp/generatediniciodesecionwidget/generated/GeneratedIngresatuemailWidget.dart';
import 'package:flutterapp/joyeriaapp/generatediniciodesecionwidget/generated/GeneratedOlvidastetucontraseaWidget.dart';
import 'package:flutterapp/joyeriaapp/generatediniciodesecionwidget/generated/GeneratedSTREETSTYLE_freefile2Widget.dart';
import 'package:flutterapp/joyeriaapp/generatediniciodesecionwidget/generated/GeneratedRectangle22Widget.dart';
import 'package:flutterapp/joyeriaapp/generatediniciodesecionwidget/generated/GeneratedRectangle2Widget.dart';
import 'package:flutterapp/joyeriaapp/generatediniciodesecionwidget/generated/GeneratedVectorWidget46.dart';
import 'package:flutterapp/joyeriaapp/generatediniciodesecionwidget/generated/GeneratedRectangle23Widget.dart';

/* Frame Inicio de Secion
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIniciodeSecionWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 410.0,
        height: 739.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 0.0,
                top: 39.0,
                right: null,
                bottom: null,
                width: 410.0,
                height: 700.0,
                child: GeneratedRectangle22Widget(),
              ),
              Positioned(
                left: 71.0,
                top: 136.0,
                right: null,
                bottom: null,
                width: 267.0,
                height: 300.0,
                child: GeneratedSTREETSTYLE_freefile2Widget(),
              ),
              Positioned(
                left: 35.0,
                top: 507.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 60.0,
                child: GeneratedBotonWidget1(),
              ),
              Positioned(
                left: 20.0,
                top: 70.0,
                right: null,
                bottom: null,
                width: 8.4375,
                height: 16.875,
                child: GeneratedVectorWidget46(),
              ),
              Positioned(
                left: 35.0,
                top: 173.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 60.0,
                child: GeneratedRectangle2Widget(),
              ),
              Positioned(
                left: 35.0,
                top: 286.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 60.0,
                child: GeneratedRectangle23Widget(),
              ),
              Positioned(
                left: 54.0,
                top: 306.0,
                right: null,
                bottom: null,
                width: 161.0,
                height: 22.0,
                child: GeneratedIngresatuemailWidget(),
              ),
              Positioned(
                left: 326.0,
                top: 310.0,
                right: null,
                bottom: null,
                width: 18.750144958496094,
                height: 12.5,
                child: GeneratedVectorWidget47(),
              ),
              Positioned(
                left: 54.0,
                top: 193.0,
                right: null,
                bottom: null,
                width: 211.0,
                height: 22.0,
                child: GeneratedIngresatuCorreoElectronicoWidget(),
              ),
              Positioned(
                left: 65.0,
                top: 360.0,
                right: null,
                bottom: null,
                width: 189.0,
                height: 22.0,
                child: GeneratedOlvidastetucontraseaWidget(),
              )
            ]),
      ),
    ));
  }
}
