import 'package:flutter/material.dart';
import 'package:flutterapp/joyeriaapp/generatedperfilwidget6/generated/GeneratedFondoWidget2.dart';
import 'package:flutterapp/joyeriaapp/generatedperfilwidget6/generated/GeneratedMiPerfilWidget.dart';
import 'package:flutterapp/joyeriaapp/generatedperfilwidget6/generated/GeneratedGuest1Widget.dart';
import 'package:flutterapp/joyeriaapp/generatedperfilwidget6/generated/GeneratedFrame4Widget.dart';
import 'package:flutterapp/joyeriaapp/generatedperfilwidget6/generated/GeneratedFrame5Widget.dart';
import 'package:flutterapp/joyeriaapp/generatedperfilwidget6/generated/GeneratedRectangle11Widget.dart';
import 'package:flutterapp/joyeriaapp/generatedperfilwidget6/generated/GeneratedUsuariosinverificarWidget.dart';
import 'package:flutterapp/joyeriaapp/generatedperfilwidget6/generated/GeneratedBarraWidget3.dart';
import 'package:flutterapp/joyeriaapp/generatedperfilwidget6/generated/GeneratedUSUARIO3Widget.dart';

/* Frame Perfil
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPerfilWidget6 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 410.0,
        height: 739.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 182, 182, 182),
                ),
              ),
              Positioned(
                left: -2.0,
                top: 10.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 644.0,
                child: GeneratedFondoWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 59.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 100.0,
                child: GeneratedRectangle11Widget(),
              ),
              Positioned(
                left: 173.0,
                top: 26.0,
                right: null,
                bottom: null,
                width: 65.0,
                height: 22.0,
                child: GeneratedMiPerfilWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 46.48944091796875,
                right: null,
                bottom: null,
                width: 124.09136962890625,
                height: 123.39324188232422,
                child: GeneratedGuest1Widget(),
              ),
              Positioned(
                left: 131.0,
                top: 70.0,
                right: null,
                bottom: null,
                width: 286.0,
                height: 94.0,
                child: GeneratedUSUARIO3Widget(),
              ),
              Positioned(
                left: 131.0,
                top: 115.0,
                right: null,
                bottom: null,
                width: 174.0,
                height: 33.0,
                child: GeneratedUsuariosinverificarWidget(),
              ),
              Positioned(
                left: 2.0,
                top: 661.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 78.0,
                child: GeneratedBarraWidget3(),
              ),
              Positioned(
                left: 31.0,
                top: 180.0,
                right: null,
                bottom: null,
                width: 351.0,
                height: 78.0,
                child: GeneratedFrame4Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 274.0,
                right: null,
                bottom: null,
                width: 350.0,
                height: 81.0,
                child: GeneratedFrame5Widget(),
              )
            ]),
      ),
    ));
  }
}
