import 'package:flutter/material.dart';
import 'package:flutterapp/joyeriaapp/generatedajusteswidget8/generated/GeneratedVectorWidget54.dart';
import 'package:flutterapp/joyeriaapp/generatedajusteswidget8/generated/GeneratedVectorWidget50.dart';
import 'package:flutterapp/joyeriaapp/generatedajusteswidget8/generated/GeneratedRectangle15Widget.dart';
import 'package:flutterapp/joyeriaapp/generatedajusteswidget8/generated/GeneratedRectangle17Widget.dart';
import 'package:flutterapp/joyeriaapp/generatedajusteswidget8/generated/GeneratedEllipse2Widget.dart';
import 'package:flutterapp/joyeriaapp/generatedajusteswidget8/generated/GeneratedUbicacionWidget.dart';
import 'package:flutterapp/joyeriaapp/generatedajusteswidget8/generated/GeneratedRectangle13Widget.dart';
import 'package:flutterapp/joyeriaapp/generatedajusteswidget8/generated/GeneratedRectangle16Widget.dart';
import 'package:flutterapp/joyeriaapp/generatedajusteswidget8/generated/GeneratedAyudaWidget.dart';
import 'package:flutterapp/joyeriaapp/generatedajusteswidget8/generated/GeneratedRectangle12Widget.dart';
import 'package:flutterapp/joyeriaapp/generatedajusteswidget8/generated/GeneratedVectorWidget53.dart';
import 'package:flutterapp/joyeriaapp/generatedajusteswidget8/generated/GeneratedInformacionWidget.dart';
import 'package:flutterapp/joyeriaapp/generatedajusteswidget8/generated/GeneratedEllipse1Widget.dart';
import 'package:flutterapp/joyeriaapp/generatedajusteswidget8/generated/GeneratedVectorWidget51.dart';
import 'package:flutterapp/joyeriaapp/generatedajusteswidget8/generated/GeneratedAjustesWidget9.dart';
import 'package:flutterapp/joyeriaapp/generatedajusteswidget8/generated/GeneratedFavoritosWidget.dart';
import 'package:flutterapp/joyeriaapp/generatedajusteswidget8/generated/GeneratedPolygon1Widget.dart';
import 'package:flutterapp/joyeriaapp/generatedajusteswidget8/generated/GeneratedComprasWidget.dart';
import 'package:flutterapp/joyeriaapp/generatedajusteswidget8/generated/GeneratedVectorWidget52.dart';
import 'package:flutterapp/joyeriaapp/generatedajusteswidget8/generated/GeneratedRectangle18Widget.dart';
import 'package:flutterapp/joyeriaapp/generatedajusteswidget8/generated/GeneratedMetododePagoWidget.dart';
import 'package:flutterapp/joyeriaapp/generatedajusteswidget8/generated/GeneratedRectangle14Widget.dart';
import 'package:flutterapp/joyeriaapp/generatedajusteswidget8/generated/GeneratedBarraWidget4.dart';

/* Frame Ajustes
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAjustesWidget8 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 410.0,
        height: 739.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 104, 136, 183),
                ),
              ),
              Positioned(
                left: 173.0,
                top: 26.0,
                right: null,
                bottom: null,
                width: 62.0,
                height: 25.0,
                child: GeneratedAjustesWidget9(),
              ),
              Positioned(
                left: -5.0,
                top: 65.0,
                right: null,
                bottom: null,
                width: 413.0,
                height: 558.0,
                child: GeneratedRectangle12Widget(),
              ),
              Positioned(
                left: 27.0,
                top: 329.0,
                right: null,
                bottom: null,
                width: 355.0,
                height: 60.0,
                child: GeneratedRectangle16Widget(),
              ),
              Positioned(
                left: 27.0,
                top: 253.0,
                right: null,
                bottom: null,
                width: 355.0,
                height: 60.0,
                child: GeneratedRectangle15Widget(),
              ),
              Positioned(
                left: 27.0,
                top: 91.0,
                right: null,
                bottom: null,
                width: 355.0,
                height: 60.0,
                child: GeneratedRectangle13Widget(),
              ),
              Positioned(
                left: 27.0,
                top: 486.0,
                right: null,
                bottom: null,
                width: 355.0,
                height: 60.0,
                child: GeneratedRectangle18Widget(),
              ),
              Positioned(
                left: 27.0,
                top: 410.0,
                right: null,
                bottom: null,
                width: 355.0,
                height: 60.0,
                child: GeneratedRectangle17Widget(),
              ),
              Positioned(
                left: 27.0,
                top: 172.0,
                right: null,
                bottom: null,
                width: 355.0,
                height: 60.0,
                child: GeneratedRectangle14Widget(),
              ),
              Positioned(
                left: 40.0,
                top: 108.0,
                right: null,
                bottom: null,
                width: 28.12299919128418,
                height: 26.25371551513672,
                child: GeneratedVectorWidget50(),
              ),
              Positioned(
                left: 43.0,
                top: 270.0,
                right: null,
                bottom: null,
                width: 22.5,
                height: 22.5,
                child: GeneratedVectorWidget51(),
              ),
              Positioned(
                left: 41.0,
                top: 189.0,
                right: null,
                bottom: null,
                width: 26.249923706054688,
                height: 26.250688552856445,
                child: GeneratedVectorWidget52(),
              ),
              Positioned(
                left: 39.0,
                top: 344.0,
                right: null,
                bottom: null,
                width: 26.25,
                height: 20.625,
                child: GeneratedVectorWidget53(),
              ),
              Positioned(
                left: 40.0,
                top: 428.0,
                right: null,
                bottom: null,
                width: 23.4375,
                height: 23.4375,
                child: GeneratedVectorWidget54(),
              ),
              Positioned(
                left: 40.0,
                top: 498.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 23.0,
                child: GeneratedEllipse1Widget(),
              ),
              Positioned(
                left: 59.04443359375,
                top: 534.880859375,
                right: null,
                bottom: null,
                width: 12.499878883361816,
                height: 25.534217834472656,
                child: GeneratedPolygon1Widget(),
              ),
              Positioned(
                left: 46.0,
                top: 503.0,
                right: null,
                bottom: null,
                width: 12.0,
                height: 12.0,
                child: GeneratedEllipse2Widget(),
              ),
              Positioned(
                left: 75.0,
                top: 106.0,
                right: null,
                bottom: null,
                width: 106.0,
                height: 35.0,
                child: GeneratedFavoritosWidget(),
              ),
              Positioned(
                left: 75.0,
                top: 500.0,
                right: null,
                bottom: null,
                width: 113.0,
                height: 35.0,
                child: GeneratedUbicacionWidget(),
              ),
              Positioned(
                left: 67.0,
                top: 425.0,
                right: null,
                bottom: null,
                width: 134.0,
                height: 35.0,
                child: GeneratedInformacionWidget(),
              ),
              Positioned(
                left: 75.0,
                top: 339.0,
                right: null,
                bottom: null,
                width: 182.0,
                height: 32.0,
                child: GeneratedMetododePagoWidget(),
              ),
              Positioned(
                left: 75.0,
                top: 268.0,
                right: null,
                bottom: null,
                width: 77.0,
                height: 35.0,
                child: GeneratedAyudaWidget(),
              ),
              Positioned(
                left: 75.0,
                top: 187.0,
                right: null,
                bottom: null,
                width: 106.0,
                height: 35.0,
                child: GeneratedComprasWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 661.0,
                right: null,
                bottom: null,
                width: 412.0,
                height: 78.0,
                child: GeneratedBarraWidget4(),
              )
            ]),
      ),
    ));
  }
}
