import 'package:flutter/material.dart';
import 'package:flutterapp/joyeriaapp/generatedregistrowidget1/generated/GeneratedOlvidastetucontraseaWidget1.dart';
import 'package:flutterapp/joyeriaapp/generatedregistrowidget1/generated/GeneratedVectorWidget48.dart';
import 'package:flutterapp/joyeriaapp/generatedregistrowidget1/generated/GeneratedIngresatuemailWidget1.dart';
import 'package:flutterapp/joyeriaapp/generatedregistrowidget1/generated/GeneratedBotonWidget2.dart';
import 'package:flutterapp/joyeriaapp/generatedregistrowidget1/generated/GeneratedRectangle24Widget.dart';
import 'package:flutterapp/joyeriaapp/generatedregistrowidget1/generated/GeneratedSTREETSTYLE_freefile3Widget.dart';
import 'package:flutterapp/joyeriaapp/generatedregistrowidget1/generated/GeneratedRectangle23Widget1.dart';
import 'package:flutterapp/joyeriaapp/generatedregistrowidget1/generated/GeneratedIngresatuCorreoElectronicoWidget1.dart';
import 'package:flutterapp/joyeriaapp/generatedregistrowidget1/generated/GeneratedRectangle22Widget1.dart';
import 'package:flutterapp/joyeriaapp/generatedregistrowidget1/generated/GeneratedVectorWidget49.dart';
import 'package:flutterapp/joyeriaapp/generatedregistrowidget1/generated/GeneratedEligeunNombreWidget.dart';
import 'package:flutterapp/joyeriaapp/generatedregistrowidget1/generated/GeneratedRectangle2Widget1.dart';

/* Frame Registro
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRegistroWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 410.0,
        height: 739.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 0.0,
                top: 39.0,
                right: null,
                bottom: null,
                width: 410.0,
                height: 700.0,
                child: GeneratedRectangle22Widget1(),
              ),
              Positioned(
                left: 72.0,
                top: 164.0,
                right: null,
                bottom: null,
                width: 267.0,
                height: 300.0,
                child: GeneratedSTREETSTYLE_freefile3Widget(),
              ),
              Positioned(
                left: 35.0,
                top: 507.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 60.0,
                child: GeneratedBotonWidget2(),
              ),
              Positioned(
                left: 20.0,
                top: 70.0,
                right: null,
                bottom: null,
                width: 8.4375,
                height: 16.875,
                child: GeneratedVectorWidget48(),
              ),
              Positioned(
                left: 35.0,
                top: 213.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 60.0,
                child: GeneratedRectangle2Widget1(),
              ),
              Positioned(
                left: 35.0,
                top: 134.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 60.0,
                child: GeneratedRectangle24Widget(),
              ),
              Positioned(
                left: 35.0,
                top: 310.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 60.0,
                child: GeneratedRectangle23Widget1(),
              ),
              Positioned(
                left: 54.0,
                top: 324.0,
                right: null,
                bottom: null,
                width: 161.0,
                height: 22.0,
                child: GeneratedIngresatuemailWidget1(),
              ),
              Positioned(
                left: 321.0,
                top: 328.0,
                right: null,
                bottom: null,
                width: 18.750144958496094,
                height: 12.5,
                child: GeneratedVectorWidget49(),
              ),
              Positioned(
                left: 54.0,
                top: 232.0,
                right: null,
                bottom: null,
                width: 211.0,
                height: 22.0,
                child: GeneratedIngresatuCorreoElectronicoWidget1(),
              ),
              Positioned(
                left: 55.0,
                top: 154.0,
                right: null,
                bottom: null,
                width: 122.0,
                height: 22.0,
                child: GeneratedEligeunNombreWidget(),
              ),
              Positioned(
                left: 65.0,
                top: 389.0,
                right: null,
                bottom: null,
                width: 189.0,
                height: 22.0,
                child: GeneratedOlvidastetucontraseaWidget1(),
              )
            ]),
      ),
    ));
  }
}
